// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
	RATE_LIMIT: KVNamespace;
	API_SECRET: string;
	RESEND_API_KEY: string;
	CONTACT_TO_EMAIL: string;
	NODEMAILER_USER: string;
	NODEMAILER_PASSWORD: string;
}
