name = "my-worker-app"
main = "src/index.ts"
compatibility_date = "2025-03-29"

# 将环境变量都放在 [vars] 下
[vars]
NODE_VERSION = "18.18.0"
YARN_VERSION = "1.22.0"
CONTACT_TO_EMAIL = "[\"187076081@qq.com\", \"xr20210530@163.com\"]"